### ISSUE TITLE
발표 준비

### ISSUE THREAD

**Issue by leegwichan** [leegwichan/MakingChallenge11#41]
✅발표는 팀별로 자유롭게 5분 정도의 분량(*시간이 너무 오바되지 않도록*)으로 준비해주세요! <주제 선정, 결과물 기능구현> 등 내용은 자유롭게 구성 가능하지만 이번 메이킹챌린지를 통해서 어떤 것을 배우고 느끼셨는지에 대한 부분은 꼭 들어갔음 합니다ㅎㅎ
발표방식은 게더 화면 공유를 통해 ppt 등 시각적으로 제작한 웹페이지를 모두가 볼 수 있도록 준비해주시면 좋을 것 같습니다🤓

✅그동안 여러분들이 열심히 만들어주신 웹페이지는 스파르타 홈페이지-'4월 전시회'에 게시됩니다! 게시를 위해 제작하신 웹사이트를 mp4로 촬영해서 제출해주셔야하는데요~! 아래 링크 함께 올려드리니 준비되신 분들은 기한(~3/20) 내 업로드해주시면 감사하겠습니다🙏🏻
👉파일 제출: http://spartacodingclub.shop/portfolio

**Comment by leegwichan** [comment]
발표 순서 ★복습1팀-3팀-2팀-심화2팀-3팀-1팀-4팀★

**Comment by leegwichan** [comment]
Wiki 작성: 
- Frontend: 윤호님
- Backend: 윤식님
발표 자료 준비: 인애님, 충안
mp4 촬영: 충안

**Comment by leegwichan** [comment]
1. 팀이름(소개) /구성원/ 역할 담당

2. 실행 하는거 소개
 - 회원가입 & 아이디 비밀번호 찾기
회원가입 화면
로그인 화면
아이디 찾기
비밀번호 찾기
 - 메인 페이지 & 상세 페이지
메인페이지 띄워놓기
카테고리 기능 ... 2가지
지도 검색 기능 
리스트 클릭시 상세페이지(내용)
함께 보면 좋은 전시들
북마크 추가 기능 / 링크 복사 / 조회수 북마크수
옆으로 넘기는 기능

 - 마이페이지 & 북마크
계정 정보 변경
북마크
회원 탈퇴/ 로그 아웃
3. 느낀 점

**Comment by leegwichan** [comment]
ppt 완성

**Comment by younhoso** [comment]
wiki 완성

**Comment by leegwichan** [comment]
발표회 종료
